### ISSUE TITLE
Duplicated class generated

### ISSUE THREAD

**Issue by AlbertoMonteiro** [mwpowellhtx/Code.Generation.Roslyn#4]
Hi, I've followed the tutorial for building a generator and in the project that I use the CodeGeneration the class Bar was duplicated.

As you can see I just pressed F12 on Bar, and it shoes 2 class, one from my file Bar.cs, and another from the generated one.

![image](https://user-images.githubusercontent.com/836496/76110645-a0d51c00-5fbd-11ea-886a-2028e53aac1b.png)

### The Bar class

```csharp
using Alberto.FastMap.CodeGen;

namespace Alberto.TheApp
{
    [ImplementCloneableInterface]
    public class Bar
    {
    }
}

```

I've used same classes that you showed in readme tutorial **ImplementCloneableInterfaceAttribute** and **ImplementCloneableInterfaceGenerator**

Thats my CodeGen project csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Code.Generation.Roslyn" Version="1.2.0.20972" />
  </ItemGroup>

</Project>

```

And that is my Client app that uses the CodeGen

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Code.Generation.Roslyn.BuildTime" Version="1.2.0.20971" PrivateAssets="all"/>
    <DotNetCliToolReference Include="dotnet-cgr" Version="[1,2)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alberto.FastMap.CodeGen\Alberto.FastMap.CodeGen.csproj" />
  </ItemGroup>

</Project>

```

**Comment by AlbertoMonteiro** [comment]
I've added empty constructor in my Bar, then when I compiled, I got this error

![image](https://user-images.githubusercontent.com/836496/76111058-60c26900-5fbe-11ea-8288-c1a9d94c3c67.png)

**Comment by AlbertoMonteiro** [comment]
@mwpowellhtx any feedback about that?

**Comment by mwpowellhtx** [comment]
@AlbertoMonteiro Hello, it's been awhile since I last worked in this actively. I'll have a look at it next day or so and see what I can find out. Thanks for bringing it to my attention.

**Comment by louthy** [comment]
@AlbertoMonteiro I haven't used this version of the `CodeGeneration.Roslyn`, but the original.  On the original there's a requirement to make your classes `partial`

**Comment by AlbertoMonteiro** [comment]
@louthy I've used the original version, it's working fine and I don't need to make them partial, only if I am going to "inject" some code.
I have found many code generation libraries, I am looking them to find the one the will be best fit to my project.

**Comment by mwpowellhtx** [comment]
@AlbertoMonteiro Without diving in more deeply, if memory serves, this is not intended to be a code analyzer. The onus is on you, the generator author, to do our due diligence for aspects such as detecting whether you have a ctor, whether the partial keyword should be injected, this sort of thing. Also, since it is not a code analyzer nor fixer, it does not replace the original code, etc. Let me know if I've missed something about it. Contributions welcome.

**Comment by AlbertoMonteiro** [comment]
@mwpowellhtx this is not my point, I am not building an analyzer, or even trying to change some class already written, I was just following the tutorial that you had on your README, but it seems that does not work, I tried to fix adding a partial keyword in my class, but still does not work.

**Comment by mwpowellhtx** [comment]
@AlbertoMonteiro It is only intended to illustrate along the lines of what's possible with this tooling. Have a look at the *Fruit Inspection* tests, perhaps? Do you have a Github where I could review your generator?

**Comment by AlbertoMonteiro** [comment]
@mwpowellhtx I will create a repo with the reproduction and let you know here

**Comment by AlbertoMonteiro** [comment]
@mwpowellhtx here is the repro repository
https://github.com/AlbertoMonteiro/CodeGenerationRoslynBugRepro

**Comment by mwpowellhtx** [comment]
@AlbertoMonteiro Hmm, well, I am receiving dotnet runtime snafus. I cloned the repo, tried to rebuild. Issue filed against the [dotnet runtime](/dotnet/runtime/issues/33520) as far as that goes.

However, I will reiterate, my goal with this CGR is to simply expose and facilitate an opportunity for CG authors to generate some code. That's it. And in a couple different scenarios, triggered by a token level annotation, or at an assembly level, which is a bit different from the original project. I also do not intend to second guess any namespaces or anything along those lines, and the artifacts you generate are at the compilation unit level, not the member level, another subtle, but key difference in stated objectives.

Specifically exercising the example:

1. Again, CGR is not a code analyzer or fixer. It is not intended to inject Roslyn keyword tokens such as `partial` in the source file.
1. Similarly, the onus is on the generator author to ensure generated artifacts land in the correct namespaces, with appropriate keyword tokens, and so on.

```
Error	CS0121	The call is ambiguous between the following methods or properties: 'Task.Run(Action, CancellationToken)' and 'Task.Run(Func<Task>, CancellationToken)'	Alberto.FastMap.CodeGen	G:\Source\Spikes\AlbertoMonteiro\CodeGenerationRoslynBugRepro\master\src\Alberto.FastMap.CodeGen\ImplementCloneableInterfaceGenerator.cs	145	Active

Error	NU1202	Package System.Reflection.Metadata 1.0.21 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package System.Reflection.Metadata 1.0.21 supports: portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)	Alberto.TheApp	G:\Source\Spikes\AlbertoMonteiro\CodeGenerationRoslynBugRepro\master\src\Alberto.TheApp\Alberto.TheApp.csproj	1	

Error	NU1202	Package System.Collections.Immutable 1.1.36 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package System.Collections.Immutable 1.1.36 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)	Alberto.TheApp	G:\Source\Spikes\AlbertoMonteiro\CodeGenerationRoslynBugRepro\master\src\Alberto.TheApp\Alberto.TheApp.csproj	1	

Error	NU1202	Package Microsoft.CodeAnalysis.CSharp 1.0.1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.CodeAnalysis.CSharp 1.0.1 supports:
 - net45 (.NETFramework,Version=v4.5)
 - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)	Alberto.TheApp	G:\Source\Spikes\AlbertoMonteiro\CodeGenerationRoslynBugRepro\master\src\Alberto.TheApp\Alberto.TheApp.csproj	1	

Error	NU1202	Package Microsoft.CodeAnalysis.Common 1.0.1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.CodeAnalysis.Common 1.0.1 supports:
 - net45 (.NETFramework,Version=v4.5)
 - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)	Alberto.TheApp	G:\Source\Spikes\AlbertoMonteiro\CodeGenerationRoslynBugRepro\master\src\Alberto.TheApp\Alberto.TheApp.csproj	1	
```

Hopefully that makes guidance along these lines a bit clearer. The runtime kerfuffle I just stumbled upon has been a festering issue, IMO. So-called LTS runtimes, `netcore2.1` in this case, seems more like a problem child. It should "just work" but apparently it does not.

Trying to test in a VS2017 environment. I do not have VS2019 at the moment, do not think I should need that, per se. Can you be more specific as to what you have installed in your environment re: Visual Studio, runtimes, etc?

**Comment by mwpowellhtx** [comment]
Just a quick update, I've identified a possible source of the issue at hand, naming in how I am referencing NuGet package versions. Apparently NuGet does not treat version ranges especially well, but does not seem to have any problems with specified wildcard versions. So I will try that and see if it does not improve things. Still aiming for `netcoreapp2.1` unless or until a case presents itself that I must update to `v3`. Not that I am opposed to that, but I want this to be as widely available as possible.
